### ISSUE TITLE
ModuleNotFoundError: No module named 'vtkmodules.web.utils'

### ISSUE THREAD

**Issue by nantille** [Kitware/py-web-vue#2]
**Describe the bug**

After `pip install pywebvue` and building the client with `npm i`, I tried launching example `03_applications/vtk-f1-picking/app.py`. I got a `ModuleNotFoundError: No module named 'vtkmodules.web.utils'`.
I've got the latest vtk python module (v9.0.3) installed.

**To Reproduce**

Follow description above

***Code***

None

**Expected behavior**

That the example launches correctly.

**Platform:**

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [x] MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [ ] Chrome
- [x] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

***py-web-vue version:***
v1.2.5

**Comment by jourdain** [comment]
9.0.3 does not include the change needed for py-web-vue. You still need to get the `dev` version of vtk (which is the same as vtk/master).

**Comment by jourdain** [comment]
Hopefully we'll get a new official release of vtk on pip which will streamline the usage of the vtk backend in 3-6 months.
In the meantime you will have to `pip install vtk --dev` instead.

**Comment by jourdain** [comment]
I was talking about any `pre-release` in the [history](https://pypi.org/project/vtk/#history) of PyPI.

Thanks for your interest in this project. I'm very excited as it should simplify quite a lot the creation of Web app/demo when using VTK or ParaView.

Thanks!

**Comment by nantille** [comment]
That helps. Yes, I've engineered an [interactive viz tool](https://github.com/int-brain-lab/iblviewer) with VTK. It relies on advanced volume and surface/point rendering that typically cannot be handled by vtkjs. We use the viewer in QT but also as standalone app but we also use Jupyter. We already have got image streaming to Jupyter working thanks to ipyvtklink-simple. Hence we're interested in streaming from vtk to a web app with pywebvue. Thanks for your work!
