### ISSUE TITLE
Failed to run on Windows

### ISSUE THREAD

**Issue by finetjul** [Kitware/py-web-vue#4]
**Describe the bug**

Not sure if it is proper to Windows or just that I did not run the correct commands

**To Reproduce**
```
$ git clone git@github.com:Kitware/py-web-vue.git
$ cd py-web-vue
$ python3 -m venv py-env
$ .\py-env\Scripts\activate
$ pip install -e .\python\
$ pip install vtk==9.0.20210717.dev0
$ python .\examples\VTK\SimpleCone\LocalRendering\app.py
-> ValueError: No directory exists at 'C:\Work\ParaviewWeb\py-web-vue\py-web-vue\python\src\pywebvue\www
```

**Platform:**
Windows 10
Python 3.7.8

***py-web-vue version:***
master > v2.0.0

**Comment by jourdain** [comment]
Where did you get `pip install -e .\python\`? I need to fix the doc as it is for developer.
If you are a user you should do `pip install pywebvue`.

To fix your issue as a `developer` you need to build the client by doing that first:

```
cd client
npm i
npm run build
```

**Comment by finetjul** [comment]
Thanks !

**Comment by jourdain** [comment]
Does it work now?

**Comment by finetjul** [comment]
Yes

(sorry btw, I did not even try to make it work)

Got tonight a bit of time to play with it, cool work !
